(function(){
  "use strict";
  var cfg=window.HERMES_CONFIG||{};
  var state={checking:false,lastOnline:null,toastTimer:null,deferredInstall:null};
  var $=function(id){return document.getElementById(id)};
  var launchers=[$("launchButton"),$("bottomLaunch")];

  function setLinks(){launchers.forEach(function(link){if(link)link.href=cfg.deploymentUrl||"#"});var source=$("sourceLink");if(source)source.href=cfg.repositoryUrl||"#"}
  function setProgress(percent){var bar=$("topProgress");bar.style.width=Math.max(0,Math.min(100,percent))+"%";bar.style.opacity=percent>=100?"0":"1"}
  function setStatus(kind,title,detail){["headerDot","mainDot"].forEach(function(id){var dot=$(id);dot.className="status-dot "+kind});$("headerStatus").textContent=kind==="online"?"Web App พร้อมใช้งาน":kind==="offline"?"เชื่อมต่อไม่ได้":"กำลังตรวจสอบ";$("mainStatus").textContent=title;$("statusDetail").textContent=detail;var badge=$("statusBadge");badge.textContent=kind==="online"?"ONLINE":kind==="offline"?"UNREACHABLE":"CHECKING";badge.className="status-badge "+kind;$("terminalText").textContent=kind==="online"?"Deployment reachable · Authentication remains private":kind==="offline"?"Health check failed · No command was sent":"Checking deployment availability…"}
  function showToast(message,isError){var toast=$("toast");clearTimeout(state.toastTimer);toast.textContent=message;toast.className="toast show"+(isError?" error":"");state.toastTimer=setTimeout(function(){toast.className="toast"},4200)}
  function formatTime(){return new Date().toLocaleString("th-TH",{dateStyle:"medium",timeStyle:"medium"})}
  function checkHealth(manual){if(state.checking)return Promise.resolve();if(!navigator.onLine){setStatus("offline","อุปกรณ์ออฟไลน์","ตรวจพบว่าอุปกรณ์ยังไม่เชื่อมต่ออินเทอร์เน็ต");return Promise.resolve(false)}state.checking=true;setStatus("checking","กำลังตรวจสอบ Web App","ส่งคำขอ Availability Check แบบไม่อ่านข้อมูลบัญชี");setProgress(22);var controller=new AbortController();var timer=setTimeout(function(){controller.abort()},Number(cfg.healthCheckTimeoutMs)||10000);return fetch(cfg.deploymentUrl,{method:"GET",mode:"no-cors",cache:"no-store",credentials:"omit",signal:controller.signal}).then(function(){state.lastOnline=true;setProgress(100);setStatus("online","Web App พร้อมใช้งาน","Deployment ตอบสนองแล้ว · เปิด Dashboard เพื่อเข้าสู่ระบบและดูข้อมูลจริง");$("lastChecked").textContent="ตรวจล่าสุด "+formatTime();if(manual)showToast("Web App พร้อมใช้งาน — ไม่ได้ส่งคำสั่งเทรด");return true}).catch(function(){state.lastOnline=false;setProgress(100);setStatus("offline","ไม่สามารถยืนยันการเชื่อมต่อ","Web App อาจต้อง Login, ถูกจำกัดสิทธิ์ หรือเครือข่ายไม่พร้อม");$("lastChecked").textContent="ตรวจไม่ผ่าน "+formatTime();if(manual)showToast("ตรวจ Web App ไม่สำเร็จ กรุณาลองเปิด Dashboard โดยตรง",true);return false}).finally(function(){clearTimeout(timer);state.checking=false;setTimeout(function(){setProgress(0)},450)})}
  function launch(event){if(!navigator.onLine){event.preventDefault();showToast("อุปกรณ์ออฟไลน์ จึงยังเปิด Dashboard ไม่ได้",true);return}var overlay=$("launchOverlay");overlay.classList.add("open");overlay.setAttribute("aria-hidden","false");setTimeout(function(){overlay.classList.remove("open");overlay.setAttribute("aria-hidden","true")},1250)}
  function copyUrl(){if(!cfg.deploymentUrl)return;navigator.clipboard.writeText(cfg.deploymentUrl).then(function(){showToast("คัดลอก Web App URL แล้ว")}).catch(function(){showToast("คัดลอกอัตโนมัติไม่ได้ กรุณาเปิด Dashboard แล้วคัดลอกจาก Address Bar",true)})}
  function onlineChanged(){var offline=!navigator.onLine;$("offlineBanner").classList.toggle("show",offline);launchers.forEach(function(link){link.setAttribute("aria-disabled",offline?"true":"false")});if(offline)setStatus("offline","อุปกรณ์ออฟไลน์","ระบบจะตรวจใหม่เมื่ออินเทอร์เน็ตกลับมา");else checkHealth(false)}
  function registerWorker(){if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js").catch(function(){})}
  function boot(){setLinks();setProgress(10);$("bootMessage").textContent="กำลังตรวจ Deployment URL…";checkHealth(false).finally(function(){setTimeout(function(){$("bootScreen").classList.add("hidden");document.body.classList.remove("is-loading")},350)});launchers.forEach(function(link){link.addEventListener("click",launch)});$("checkButton").addEventListener("click",function(){checkHealth(true)});$("copyButton").addEventListener("click",copyUrl);window.addEventListener("online",onlineChanged);window.addEventListener("offline",onlineChanged);onlineChanged();registerWorker();setInterval(function(){if(!document.hidden)checkHealth(false)},Number(cfg.healthCheckIntervalMs)||60000)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();
